CREATE TABLE IF NOT EXISTS keyword_progress (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  keyword TEXT NOT NULL UNIQUE,
  cluster TEXT NOT NULL,
  monthly_volume INTEGER,
  keyword_difficulty INTEGER,
  priority_period TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'published', 'ranking', 'page1')),
  published_date TIMESTAMPTZ,
  ranking_position INTEGER,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE keyword_progress ADD COLUMN IF NOT EXISTS cluster TEXT;
ALTER TABLE keyword_progress ADD COLUMN IF NOT EXISTS priority_period TEXT;

CREATE INDEX IF NOT EXISTS keyword_progress_cluster_idx ON keyword_progress(cluster);
CREATE INDEX IF NOT EXISTS keyword_progress_status_idx ON keyword_progress(status);

INSERT INTO keyword_progress (keyword, cluster, monthly_volume, keyword_difficulty, priority_period, status)
VALUES
('tattoo pain chart', 'Golden Triangle', 27100, 15, 'WEEK 1', 'pending'),
('tattoo removal near me', 'Golden Triangle', 27100, 9, 'WEEK 1', 'pending'),
('how long does it take for a tattoo to heal', 'Golden Triangle', 14800, 15, 'WEEK 1', 'pending'),
('tattoo meaning of a semicolon', 'Golden Triangle', 14800, 14, 'WEEK 1', 'pending'),
('tattoo styles', 'Golden Triangle', 14800, 14, 'WEEK 2', 'pending'),
('tattoo aftercare instructions', 'Golden Triangle', 9900, 10, 'WEEK 1', 'pending'),
('tattoo of a butterfly meaning', 'Golden Triangle', 9900, 5, 'WEEK 1', 'pending'),
('tattoo of butterfly meaning', 'Golden Triangle', 9900, 5, 'WEEK 1', 'pending'),
('mild soap for tattoo aftercare', 'Golden Triangle', 9900, 11, 'WEEK 2', 'pending'),
('tattoo healing process', 'Golden Triangle', 9900, 14, 'WEEK 2', 'pending'),
('butterfly tattoo definition', 'Golden Triangle', 9900, 6, 'WEEK 1', 'pending'),
('snake tattoo meaning', 'Golden Triangle', 8100, 7, 'WEEK 1', 'pending'),
('tattoo aftercare cream', 'Golden Triangle', 6600, 8, 'WEEK 2', 'pending'),
('tattoo lotion', 'Golden Triangle', 6600, 10, 'WEEK 2', 'pending'),
('tattoo prices', 'Golden Triangle', 6600, 13, 'WEEK 3', 'pending'),
('tattoo hurt scale', 'Golden Triangle', 6600, 14, 'WEEK 3', 'pending'),
('tattoo aftercare products', 'Golden Triangle', 6600, 14, 'WEEK 3', 'pending'),
('how much do tattoos cost', 'Golden Triangle', 6600, 14, 'WEEK 3', 'pending'),
('tattoo peeling', 'Golden Triangle', 5400, 15, 'WEEK 4', 'pending'),
('best numbing cream for tattoos', 'Golden Triangle', 5400, 15, 'WEEK 4', 'pending'),
('tattoo shark meaning', 'Golden Triangle', 4400, 5, 'WEEK 2', 'pending'),
('walk in tattoos near me', 'Golden Triangle', 3600, 5, 'WEEK 2', 'pending'),
('least painful tattoo spots', 'Golden Triangle', 2400, 6, 'WEEK 3', 'pending'),
('places tattoos hurt least', 'Golden Triangle', 2400, 6, 'WEEK 3', 'pending'),
('blackwork tattoo style', 'Golden Triangle', 880, 2, 'WEEK 4', 'pending'),
('medusa tattoo meaning', 'Meaning', 40500, 25, 'MONTH 2', 'pending'),
('semicolon tattoo significance', 'Meaning', 14800, 15, 'MONTH 2', 'pending'),
('butterfly tattoo meaning', 'Meaning', 22200, 27, 'MONTH 3', 'pending'),
('lotus tattoo meaning', 'Meaning', 3600, 14, 'MONTH 2', 'pending'),
('rose tattoo meaning', 'Meaning', 3600, 14, 'MONTH 2', 'pending'),
('scorpion tattoo meaning', 'Meaning', 2900, 13, 'MONTH 2', 'pending'),
('swallow tattoo meaning', 'Meaning', 3600, 11, 'MONTH 2', 'pending'),
('dragon tattoo meaning', 'Meaning', 2900, 9, 'MONTH 2', 'pending'),
('meaningful tattoos', 'Meaning', 8100, 21, 'MONTH 3', 'pending'),
('dandelion tattoo meaning', 'Meaning', 6600, 23, 'MONTH 3', 'pending'),
('lotus flower tattoo meaning', 'Meaning', 6600, 22, 'MONTH 3', 'pending'),
('444 tattoo meaning', 'Meaning', 9900, 26, 'MONTH 4', 'pending'),
('koi fish and dragon tattoo meaning', 'Meaning', 2900, 14, 'MONTH 2', 'pending'),
('spider web tattoo meaning', 'Meaning', 2900, 14, 'MONTH 2', 'pending'),
('rose tattoo colour meaning', 'Meaning', 2400, 13, 'MONTH 2', 'pending'),
('tribal tattoos designs and meanings', 'Meaning', 1900, 12, 'MONTH 3', 'pending'),
('skeleton hand tattoo meaning', 'Meaning', 1300, 13, 'MONTH 3', 'pending'),
('meaningful front thigh tattoos', 'Meaning', 1300, 12, 'MONTH 3', 'pending'),
('tattoo numbing cream', 'Aftercare', 33100, 23, 'MONTH 4', 'pending'),
('numbing cream for tattoos', 'Aftercare', 18100, 28, 'MONTH 4', 'pending'),
('tattoo aftercare tattoo', 'Aftercare', 18100, 20, 'MONTH 3', 'pending'),
('how long do tattoos take to heal', 'Aftercare', 8100, 24, 'MONTH 4', 'pending'),
('fragrance free lotion for tattoo aftercare', 'Aftercare', 6600, 24, 'MONTH 4', 'pending'),
('best tattoo numbing cream', 'Aftercare', 6600, 29, 'MONTH 5', 'pending'),
('aquaphor for tattoo aftercare', 'Aftercare', 5400, 27, 'MONTH 5', 'pending'),
('tattoo aftercare derm shield patch', 'Aftercare', 5400, 19, 'MONTH 4', 'pending'),
('tattoo cream', 'Aftercare', 4400, 15, 'MONTH 3', 'pending'),
('tattoo aftercare with aquaphor', 'Aftercare', 4400, 27, 'MONTH 5', 'pending'),
('scentless lotion for tattoos', 'Aftercare', 4400, 25, 'MONTH 5', 'pending'),
('tattoo placement', 'Placement', 2900, 14, 'MONTH 4', 'pending'),
('tattoo placement chart', 'Placement', 1300, 7, 'MONTH 4', 'pending'),
('tattoo pain chart female', 'Placement', 4400, 19, 'MONTH 4', 'pending'),
('most painful tattoo spots', 'Placement', 3600, 11, 'MONTH 3', 'pending'),
('most painful places to get a tattoo', 'Placement', 2400, 19, 'MONTH 4', 'pending'),
('tattoo placements', 'Placement', 1300, 14, 'MONTH 4', 'pending'),
('tattoo ideas on shoulder for women', 'Placement', 1000, 10, 'MONTH 3', 'pending'),
('tattoo pain chart men', 'Placement', 2400, 16, 'MONTH 4', 'pending'),
('pain scale of tattoos', 'Placement', 1900, 16, 'MONTH 4', 'pending'),
('first tattoo ideas', 'Placement', 3600, 29, 'MONTH 6', 'pending'),
('walk in tattoo shops near me', 'Commercial', 18100, 25, 'MONTH 9', 'pending'),
('body piercing and tattoo near me', 'Commercial', 12100, 12, 'MONTH 6', 'pending'),
('laser tattoo removal near me', 'Commercial', 9900, 9, 'MONTH 6', 'pending'),
('henna tattoo near me', 'Commercial', 9900, 22, 'MONTH 9', 'pending'),
('tattoo and piercing shops near me', 'Commercial', 9900, 22, 'MONTH 9', 'pending'),
('eyebrow tattoo near me', 'Commercial', 6600, 18, 'MONTH 9', 'pending'),
('female tattoo artists', 'Commercial', 2900, 16, 'MONTH 6', 'pending'),
('tattoo apprenticeship near me', 'Commercial', 2900, 9, 'MONTH 9', 'pending'),
('friday the 13th tattoos near me', 'Commercial', 2400, 10, 'MONTH 9', 'pending'),
('american traditional tattoo artists near me', 'Commercial', 720, 4, 'MONTH 6', 'pending'),
('book tattoo', 'Commercial', 2900, 25, 'MONTH 9', 'pending'),
('tattoo studio', 'Commercial', 4400, 28, 'YEAR 2', 'pending'),
('how much to tip tattoo artist', 'Commercial', 5400, 21, 'MONTH 6', 'pending')
ON CONFLICT (keyword) DO NOTHING;
