import { NextRequest, NextResponse } from "next/server";
import { fal } from "@fal-ai/client";

// Clean up FAL_KEY from env.local if it has quotes
if (process.env.FAL_KEY) {
  process.env.FAL_KEY = process.env.FAL_KEY.replace(/^["']|["']$/g, "");
}

const STYLE_PROMPTS: Record<string, string> = {
  "fine-line": "fine-line style, ultra-thin single-needle linework, delicate details, negative space, clean vector-like design",
  "blackwork": "blackwork style, solid black ink fills, high-contrast silhouette, bold graphic linework, no shading",
  "neo-traditional": "neo-traditional style, bold outer lines, illustrative details, modern stylized composition, rich linework depth",
  "japanese": "traditional Japanese Irezumi style, classic waves, clouds, windbars, clean stylized line art",
  "geometric": "geometric style, perfect circles, clean straight lines, sacred geometry details, symmetry, minimal linework",
  "dotwork": "dotwork stippling style, shading made of tiny ink dots, peppered texture, fine-line outlines",
  "realism": "fine realism style, soft black and grey shading gradients, realistic textures, photographic reference style",
  "watercolor": "watercolor style, soft color washes, colorful paint splashes, abstract fluid gradients with light outlines",
  "tribal": "traditional tribal style, solid black abstract curved shapes, sharp points, ancient flow lines"
};

export async function POST(req: NextRequest) {
  try {
    const { prompt, style, aspectRatio = "square" } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    if (!process.env.FAL_KEY) {
      return NextResponse.json({ error: "FAL_KEY is not configured in environment" }, { status: 500 });
    }

    // Build optimized tattoo prompt
    const chosenStyleText = STYLE_PROMPTS[style] || STYLE_PROMPTS["fine-line"];
    const fullPrompt = `A professional tattoo design of: ${prompt}. ${chosenStyleText}. Pure white background, isolated flash sheet, clean line art, no body parts, no skin textures, perfect contrast for stencil maker.`;

    // Aspect ratio map
    let imageSize: any = "square";
    if (aspectRatio === "portrait") {
      imageSize = "portrait_4_3";
    } else if (aspectRatio === "landscape") {
      imageSize = "landscape_4_3";
    }

    // Call Fal.ai Flux Schnell model
    const result: any = await fal.subscribe("fal-ai/flux/schnell", {
      input: {
        prompt: fullPrompt,
        image_size: imageSize,
        num_inference_steps: 4,
        enable_safety_checker: true,
        sync_mode: true
      }
    });

    const imageUrl = result.images?.[0]?.url;

    if (!imageUrl) {
      return NextResponse.json({ error: "No image was generated by the AI" }, { status: 500 });
    }

    return NextResponse.json({ imageUrl, prompt: fullPrompt, success: true });
  } catch (err: any) {
    console.error("AI Generation error:", err);
    return NextResponse.json({ error: err.message || "Failed to generate image" }, { status: 500 });
  }
}
