-- TABLE: Track unique viewer interactions to build collaborative filtering dataset
CREATE TABLE IF NOT EXISTS public.post_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL, -- Unique per browser session
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for speed
CREATE INDEX IF NOT EXISTS idx_post_interactions_post_id ON public.post_interactions(post_id);
CREATE INDEX IF NOT EXISTS idx_post_interactions_session_id ON public.post_interactions(session_id);

-- FUNCTION: Smart Weighted Recommendation Engine for Posts
-- TIER 1: Collaborative (Users who read Post A also read Post B)
-- TIER 2: Contextual (Shared Category + Overlapping Tags)
CREATE OR REPLACE FUNCTION get_smart_related_posts(
    current_post_id UUID, 
    target_category TEXT, 
    target_tags TEXT[], 
    limit_count INT DEFAULT 3
)
RETURNS SETOF public.posts AS $$
BEGIN
    RETURN QUERY
    WITH collaborative_matches AS (
        -- Score 10 points per unique session overlap
        SELECT i2.post_id, COUNT(DISTINCT i2.session_id) * 10 as weight
        FROM post_interactions i1
        JOIN post_interactions i2 ON i1.session_id = i2.session_id
        WHERE i1.post_id = current_post_id
          AND i2.post_id != current_post_id
        GROUP BY i2.post_id
    ),
    content_matches AS (
        -- Score 5 points for matching category + 3 points per overlapping tag
        SELECT 
            p.id as post_id,
            ((CASE WHEN p.category = target_category THEN 5 ELSE 0 END) + 
             (cardinality(ARRAY(SELECT unnest(p.tags) INTERSECT SELECT unnest(target_tags))) * 3)) as weight
        FROM public.posts p
        WHERE p.id != current_post_id
          AND p.is_published = true
          AND (p.category = target_category OR p.tags && target_tags)
    ),
    combined_scores AS (
        SELECT post_id, SUM(weight) as total_weight
        FROM (
            SELECT * FROM collaborative_matches
            UNION ALL
            SELECT * FROM content_matches
        ) s
        GROUP BY post_id
    )
    SELECT p.*
    FROM public.posts p
    LEFT JOIN combined_scores cs ON p.id = cs.post_id
    WHERE p.id != current_post_id
      AND p.is_published = true
      AND p.deleted_at IS NULL
    ORDER BY COALESCE(cs.total_weight, 0) DESC, p.published_at DESC
    LIMIT limit_count;
END;
$$ LANGUAGE plpgsql STABLE;
